name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. چک‌اوت کد پروژه
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. تنظیم JDK برای ساخت پروژه
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. ذخیره فایل Keystore از GitHub Secrets
      - name: Decode Keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: |
          echo $KEYSTORE_FILE | base64 -d > mynewkeystore.jks

      # 4. اعطای دسترسی به Gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 5. ساخت APK امضاشده
      - name: Build Release APK
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/mynewkeystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      # 6. آپلود APK به عنوان آرتیفکت
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
